### ISSUE TITLE
This plugin won't install under windows

### ISSUE THREAD

**Issue by danships** [KELiON/cerebro-shell#1]
When I type `plugins shell` and select to shell plugin and 'Install', the Install label changes to _Installing. App will be reloaded..._

But when I type `$ echo yes` nothing happens. When I type `plugins shell` again, I see that the plugin has the install option again. So it does not seem to be installed.

**Comment by benadamstyles** [comment]
Getting the same behaviour on macOS. Cerebro v0.2.1

**Comment by KELiON** [comment]
@Leeds-eBooks hm, on mac it should work. Can you try to turn-on developer mode in Cerebro preferences, restart the application, open developer tools by `alt+cmd+I` and check if there any errors when you try to use it?

**Comment by benadamstyles** [comment]
@KELiON Nothing in the console I'm afraid.

**Comment by KELiON** [comment]
@Leeds-eBooks can you send me a gif or screenshot? Also, can you check that in dev tools on top, in group "Load external plugins" you see "Plugin: cerebro-shell"?

**Comment by benadamstyles** [comment]
@KELiON I don't see `Plugin: cerebro-shell` among the others because it never installs – as the OP says, it just hangs on _Installing. App will be reloaded..._

**Comment by danships** [comment]
@KELiON Is there a way to open the developer console on windows? Maybe the console will display something at the time of attempting to install the plugin.

**Comment by KELiON** [comment]
@Leeds-eBooks does it happen only with cerebro-shell? Can you install other plugins?

**Comment by KELiON** [comment]
@matueranet I'm not sure, but maybe `alt+windows+I` will open it

**Comment by danships** [comment]
@KELiON No, unfortunately not. For me, other plugins do install. The problem is only with cerebro-shell.

**Comment by benadamstyles** [comment]
Same here, all other plugins install fine. @matueranet I think it's either `ctrl + alt + i` or `ctrl + shift + i` on windows.

**Comment by danships** [comment]
@Leeds-eBooks already tried different combinations, those did not work unfortunately. Do you see something in the console log when installing the plugin?

**Comment by benadamstyles** [comment]
@matueranet Nothing at all.

**Comment by KELiON** [comment]
@Leeds-eBooks if your are doing it on mac, can you try please to share output of this commands in your terminal:

```
cd ~/Library/Application\ Support/Cerebro/plugins/
ls ./node_modules
cat ./package.json
````

You should see something like this: 
![image](https://cloud.githubusercontent.com/assets/594298/22156816/41468686-df35-11e6-877f-ef67ab95bd79.png)

**Comment by benadamstyles** [comment]
Output of `ls`:
```
cerebro-emoj         cerebro-imdb         cerebro-kill         cerebro-osx-define
cerebro-gif          cerebro-ip           cerebro-osx-contacts cerebro-osx-system
```

Output of `cat`:
```
{"name":"cerebro-plugins","dependencies":{"cerebro-imdb":"^0.0.4","cerebro-gif":"^0.2.1","cerebro-kill":"^0.1.1","cerebro-emoj":"^0.2.3","cerebro-ip":"^0.1.2","cerebro-osx-system":"^0.0.4","cerebro-osx-contacts":"^0.0.1","cerebro-osx-define":"^0.0.1"}}
```

**Comment by benadamstyles** [comment]
Neither includes `cerebro-shell`

**Comment by KELiON** [comment]
@matueranet @Leeds-eBooks can you try to install this plugins again? I found this issue and for me it is fixed

**Comment by benadamstyles** [comment]
It worked! Great stuff, thanks!

**Comment by danships** [comment]
@KELiON Installation now works, so that is great. Only executing the commands themselves doesn't work. If I for example type `$ echo hello`, then I do not see _hello_ as output in the console window. The window freezes. But that is something for a different issue I guess.

**Comment by KELiON** [comment]
@matueranet exactly, I'll fix it (currently works only on mac and probably on linux)

**Comment by MohitSG96** [comment]
shell executes the command but it doesn't show the output as shown in picture
