### ISSUE TITLE
History fuzzy search

### ISSUE THREAD

**Issue by eyalev** [KELiON/cerebro-shell#10]
Is there an option for commands history fuzzy-search?

Something like fzf (https://github.com/junegunn/fzf)

**Comment by KELiON** [comment]
@eyalev nope! And I don't have plans to implement it now, because I think consistency through all plugins is important, but currently generic search in plugins is not fuzzy. Probably later I'll add some option in settings to turn fuzzy search on, so it work in all plugins (not only here).
