### ISSUE TITLE
Pressing return key closes cerebro

### ISSUE THREAD

**Issue by Prn-Ice** [KELiON/cerebro-shell#13]
![deepin-screen-recorder_select area_20190305174450](https://user-images.githubusercontent.com/48252841/53821976-19e70100-3f6f-11e9-95f1-4ffbc23a93e6.gif)
Pressing enter closes cerebro and I'm on the latest version.

**Comment by milkovsky** [comment]
I can configm the issue.
Ubuntu 18.04.2 LTS
Cerebro 0.3.2
Current workarround: uncheck Clean esults on hide" in cerbro settings.
Cerebro-Shell: 0.1.7.

Maybe related: https://github.com/KELiON/cerebro-shell/issues/4

**Comment by Prn-Ice** [comment]
Thanks sorry i'm responding so late.
