### ISSUE TITLE
macOS Sierra 10.12.3 (16D32) Plugin Doesn't Work

### ISSUE THREAD

**Issue by istocniks** [KELiON/cerebro-shell#2]
Typing `$ pwd` and hitting Enter doesn't do anything for me, are there any local logs that I could send you for debugging?

**Comment by m-thomson** [comment]
Same issue here. Enter key doesn't seem to have any effect. Other plugins work.

<img width="843" alt="screenshot_2dfce6" src="https://cloud.githubusercontent.com/assets/5273016/22400539/b5f27048-e56c-11e6-85f2-a96582b2d841.png">

In case it's relevant, I'm using Bash 4 (installed via brew):

`brew install bash`

**Comment by KELiON** [comment]
@istocniks @m-thomson yes, you can check console for that. 

1) Type settings and turn on developer mode, turn on "show in menu bar";
2) Toggle Cerebro window and from tray menu select development → dev tools (main), switch to `console` tab;
3) Reload everything (development → reload);
4) Try to use shell plugin and check what do you have in console;


can you turn on developer mode in preferences, open dev-tools from tray menu  → development → dev tools (main)  and check what do you have in console?

**Comment by istocniks** [comment]
Huston, we have a problem, nothing happens when I click development → dev tools (main)
You should think of adding a standard mac os logging that would be seen in the standard mac os console app

**Comment by KELiON** [comment]
@istocniks I think I know what you mean:) Probably dev tools are shown under other application. Try to set focus to main cerebro window and use <kbd>cmd+~</kbd> to switch between windows.

**Comment by istocniks** [comment]
![screen shot 2017-01-30 at 10 51 27 am](https://cloud.githubusercontent.com/assets/1018740/22436715/1a51a158-e6da-11e6-93ed-6ae0f0cc2391.png)
got it! here's what I've got

**Comment by KELiON** [comment]
@istocniks can you click on the triangle on the left side of error to see stacktrace of the exception?

**Comment by istocniks** [comment]
![screen shot 2017-01-30 at 11 26 09 am](https://cloud.githubusercontent.com/assets/1018740/22437931/eb177f70-e6de-11e6-9196-5fe689a170fd.png)
here it is

**Comment by KELiON** [comment]
@istocniks can you try new version of this plugin?

**Comment by istocniks** [comment]
Works now, thanks!
