### ISSUE TITLE
Doesn't seem to work on Ubuntu Linux

### ISSUE THREAD

**Issue by nazar-pc** [KELiON/cerebro-shell#4]
![2017-02-10 02-23-27](https://cloud.githubusercontent.com/assets/928965/22809001/f35a7b9a-ef37-11e6-868b-5fb4ca293889.png)
Pressing Enter, Ctrl+Enter, Enter on Numpad - no effect. My shell is `fish` and terminal emulator `terminator`, but I'm not sure they are the reason why it doesn't work.
Have you tested this plugin on Linux (it is not marked as OS X-specific).

**Comment by KELiON** [comment]
@nazar-pc can you try new version? I hope I've fixed it, at least it works on Ubuntu 16 for me, but I've tried it only with bash on Ubuntu and zsh on Mac, never tried it in fish.

**Comment by nazar-pc** [comment]
Thanks! This issue is now resolved.
