### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by marcosmesser** [KELiON/cerebro-shell#8]
![2017-03-02](https://cloud.githubusercontent.com/assets/2346763/23507973/43812eec-ff2e-11e6-9490-e5442fb54fd8.png)

Some characters are not displayed correctly. 

Code page is 850.

Windows 10 Pro 64-bit 1067 14393.693.

**Comment by KELiON** [comment]
@marcosmesser can you please run the same `ping google.com` command in your terminal and paste output here?

**Comment by marcosmesser** [comment]
![image](https://cloud.githubusercontent.com/assets/2346763/23578448/f087316c-00b5-11e7-9c96-fbf1b0b0ed85.png)

The result is as expected.

Probably, the encoding needs to be set to UTF-8 somewhere, it seems that it's defaulting to ASCII.

**Comment by dubisdev** [comment]
This seems to be more a Windows issue than a Cerebro issue.

Maybe this answer can help:

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window

I was also having issues with this and now it is working

![image](https://user-images.githubusercontent.com/77246331/202520031-eb488195-9ab3-46b6-a43f-7f03754813d9.png)

Just follow the steps in the first answer and it should work.
